### ISSUE TITLE
Cannot cast.

### ISSUE THREAD

**Issue by theAeon** [theAeon/RokuKastFF#2]
Entirely broken, as per https://addons.mozilla.org/en-US/firefox/addon/rokukast-ff/reviews/1628598/

IP address does not appear to be saving.

**Comment by theAeon** [comment]
Whoops. Merged.

**Comment by nhlinux** [comment]
RokuKastFF is no good! I entered my Roku TV's. IP.  & it wouldn't connect my web browser to my tv. I had to delete this useless extension. I doubt if this issue will ever be resolved!
